# Generated by Django 4.1.1 on 2022-09-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_lent',
            field=models.BooleanField(default=False),
        ),
    ]
