name: Unit Tests
on: [pull_request, push]
jobs:
  Code_verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.7' 
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "."
          strict: "medium"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          django: true
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.7' 
      - name: Install Dependencies
        run: pip install -r requirements.txt 
      - run: ls
      - name: Build Docker-compose Stack
        run: docker-compose up -d
      - run: docker-compose run web python manage.py test
